FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./bun.lock     ./bun.lock 

COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install 
RUN bun run db:generate

EXPOSE 8080
CMD [ "bun", "run", "start:backend" ]



#NOTE- for a express server building a docker image does not 
# require db url but in nextjs it does. And bun runs backend TS files no need to build